spring.application.name: trading

spring.profiles.active: dev

spring:
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    root: INFO
    org.springframework: INFO

trading:
  pairs:
    - BTCUSDT
    - ETHUSDT

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: basic
  retryer:
    period: 500
    maxPeriod: 1000
    maxAttempts: 2
