spring:
  datasource:
    url: jdbc:h2:mem:test_db;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: never